/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#include "ABCFlow.h"
  Integrator* maker()
  {
    return new ABCFlowIntegrator;
  }

  class ABCFlowProxy
  {
    public:
      ABCFlowProxy()
      {
        Factory["ABCFlow"] = maker;
      }
  };

  ABCFlowProxy p;
