/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#include "DrivenDuffingOscillator.h"
  Integrator* maker()
  {
    return new DrivenDuffingOscillatorIntegrator;
  }

  class DrivenDuffingOscillatorProxy
  {
    public:
      DrivenDuffingOscillatorProxy()
      {
        Factory["Duffing Oscillator, Driven"] = maker;
      }
  };

  DrivenDuffingOscillatorProxy p;
