/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#include "DrivenPendulum.h"
  Integrator* maker()
  {
    return new DrivenPendulumIntegrator;
  }

  class DrivenPendulumProxy
  {
    public:
      DrivenPendulumProxy()
      {
        Factory["Pendulum, Driven"] = maker;
      }
  };

  DrivenPendulumProxy p;
