/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#include "DrivenVanDerPol.h"
  Integrator* maker()
  {
    return new DrivenVanDerPolIntegrator;
  }

  class DrivenVanDerPolProxy
  {
    public:
      DrivenVanDerPolProxy()
      {
        Factory["van der Pol, Driven"] = maker;
      }
  };

  DrivenVanDerPolProxy p;
