/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#ifndef OWL_INCLUDED_
#define OWL_INCLUDED_

#include "BaseModel.h"
#include "RungeKutta4.h"

#include "OwlParameterDialog.h"

class Owl : public DynamicalModel
{
  Scalar a;
  Scalar b;
  Scalar c;
public:
  Owl(Scalar A, Scalar B, Scalar C)
     : a(A), b(B), c(C)
  { }

  virtual ~Owl() { }

  virtual Vector exact(const Point& p) const
    {
      return Vector(-a*(p[0]+p[1]),-p[1] - b*p[0]*p[2],10.*p[0]*p[1] + c);
    }

private:
  virtual void _setValue(const std::string& name, Scalar value)
    {
      if      (name == "a") a = value;
      else if (name == "b") b = value;
      else if (name == "c") c = value;
    }
};

class OwlIntegrator : public Integrator
{
  Owl* dynamics;
  RungeKutta4<Owl>* integrator;
public:
  OwlIntegrator()
    {
      dynamics = new Owl(10., 10., 13.);
      double stepSize = 0.01;
      integrator = new RungeKutta4<Owl>(*dynamics, stepSize);
    }

  virtual ~OwlIntegrator()
    {
      delete dynamics;
      delete integrator;
    }

  inline Vector step(const Point& p)
    {
      return integrator->step(p);
    }

  virtual unsigned int getModelVersion()
    {
      return dynamics->getModelVersion();
    }

  virtual CaveDialog* createParameterDialog(GLMotif::PopupMenu *parent)
    {
      return new OwlParameterDialog(parent, dynamics);
    }

  virtual Vrui::Point center() const
    {
      return Vrui::Point(0.0, 0.0, 0);
    }
};

#endif
