/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#include "RabinovichFabrikant.h"
  Integrator* maker()
  {
    return new RabinovichFabrikantIntegrator;
  }

  class RabinovichFabrikantProxy
  {
    public:
      RabinovichFabrikantProxy()
      {
        Factory["Rabinovich-Fabrikant"] = maker;
      }
  };

  RabinovichFabrikantProxy p;
