/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#ifndef RIKITAKEDYNAMOPARAMETERDIALOG_H_
#define RIKITAKEDYNAMOPARAMETERDIALOG_H_

#include <GLMotif/GLMotif>

#include "BaseModel.h"
#include "CaveDialog.h"

class RikitakeDynamoParameterDialog : public CaveDialog
{
  typedef std::vector<GLMotif::ToggleButton*> ToggleArray;

  DynamicalModel* model;

  GLMotif::Slider *nuParameterSlider;
  GLMotif::Slider *aParameterSlider;

  GLMotif::TextField *currentNuValue;
  GLMotif::TextField *currentAValue;

  GLMotif::Slider       *stepSizeSlider;
  GLMotif::TextField    *stepSizeValue;


  GLMotif::Slider *xSpacingSlider;
  GLMotif::Slider *ySpacingSlider;
  GLMotif::Slider *zSpacingSlider;
  GLMotif::TextField *currentXValue;
  GLMotif::TextField *currentYValue;
  GLMotif::TextField *currentZValue;
  void sliderCallback(GLMotif::Slider::ValueChangedCallbackData* cbData);
  void evalTogglesCallback(GLMotif::ToggleButton::ValueChangedCallbackData* cbData);

  ToggleArray evalToggles;

protected:
  GLMotif::PopupWindow* createDialog();

public:
  RikitakeDynamoParameterDialog(GLMotif::PopupMenu *parentMenu, DynamicalModel* m)
     : CaveDialog(parentMenu), model(m)
  {
    dialogWindow=createDialog();
  }

  virtual ~RikitakeDynamoParameterDialog() { }
};

#endif
