/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#include "ShawDrivenVanDerPol.h"
  Integrator* maker()
  {
    return new ShawDrivenVanDerPolIntegrator;
  }

  class ShawDrivenVanDerPolProxy
  {
    public:
      ShawDrivenVanDerPolProxy()
      {
        Factory["van der Pol, Shaw's Driven"] = maker;
      }
  };

  ShawDrivenVanDerPolProxy p;
