/*
 * DO NOT EDIT THIS FILE.
 *
 * THIS FILE HAS BEEN AUTOMATICALLY GENERATED.
 * ANY CHANGES MADE TO THE CODE WILL BE LOST.
 *
 * TO MODIFY THE PARAMETER VALUES OR DYNAMICAL
 * EQUATIONS EDIT THE XML FILE (dynamics.xml).
 * 
 */
 
#ifndef SHAWDRIVENVANDERPOL_INCLUDED_
#define SHAWDRIVENVANDERPOL_INCLUDED_

#include "BaseModel.h"
#include "RungeKutta4.h"

#include "ShawDrivenVanDerPolParameterDialog.h"

class ShawDrivenVanDerPol : public DynamicalModel
{
  Scalar u;
  Scalar r;
  Scalar k;
  Scalar A;
  Scalar w;
public:
  ShawDrivenVanDerPol(Scalar U, Scalar R, Scalar K, Scalar A, Scalar W)
     : u(U), r(R), k(K), A(A), w(W)
  { }

  virtual ~ShawDrivenVanDerPol() { }

  virtual Vector exact(const Point& p) const
    {
      return Vector(p[2] + A*sin(p[1]),w,-k*p[0] + u*p[2]*(r-p[0]*p[0]));
    }

private:
  virtual void _setValue(const std::string& name, Scalar value)
    {
      if      (name == "u") u = value;
      else if (name == "r") r = value;
      else if (name == "k") k = value;
      else if (name == "A") A = value;
      else if (name == "w") w = value;
    }
};

class ShawDrivenVanDerPolIntegrator : public Integrator
{
  ShawDrivenVanDerPol* dynamics;
  RungeKutta4<ShawDrivenVanDerPol>* integrator;
public:
  ShawDrivenVanDerPolIntegrator()
    {
      dynamics = new ShawDrivenVanDerPol(10., .1, .7, .25, 1.57);
      double stepSize = 0.01;
      integrator = new RungeKutta4<ShawDrivenVanDerPol>(*dynamics, stepSize);
    }

  virtual ~ShawDrivenVanDerPolIntegrator()
    {
      delete dynamics;
      delete integrator;
    }

  inline Vector step(const Point& p)
    {
      return integrator->step(p);
    }

  virtual unsigned int getModelVersion()
    {
      return dynamics->getModelVersion();
    }

  virtual CaveDialog* createParameterDialog(GLMotif::PopupMenu *parent)
    {
      return new ShawDrivenVanDerPolParameterDialog(parent, dynamics);
    }

  virtual Vrui::Point center() const
    {
      return Vrui::Point(0.0, 0.0, 0.0);
    }
};

#endif
